module.exports = [
"<h3>26. Confidentiality, Intellectual Property &amp; Non-Disclosure</h3>",
"<p>In the course of employment with __COMPANY__ (hereinafter referred to as the Company), every employee is, or may be, exposed to information that is confidential, proprietary and commercially sensitive. The garment manufacturing business is highly competitive and depends substantially on the protection of designs, technical know-how, costing structures and trade relationships. The obligations set out in this chapter apply to all employees without exception, including factory workers, tailors, cutting masters, designers, merchandisers, quality controllers, sales and marketing staff, accounts personnel and members of management. These obligations are a fundamental condition of employment.</p>",
"<h4>26.1 Definition of Confidential Information</h4>",
"<p>For the purposes of this handbook, Confidential Information means any and all non-public information relating to the business, operations, customers, suppliers and finances of the Company, in whatever form it is held or recorded, whether marked confidential or not. Without limiting the generality of the foregoing, Confidential Information includes the following categories.</p>",
"<ul>",
"<li>Designs, sketches, artwork, embroidery and print files, tech packs, measurement charts, grading rules, marker plans and paper or digital patterns developed by or for the Company or any buyer.</li>",
"<li>Sample garments, prototypes, trims, fabric swatches, colour standards (lab dips) and any physical articles created during product development.</li>",
"<li>Costing sheets, cost-to-make calculations, consumption norms, wastage allowances, fabric and trim prices, labour rates, overhead absorption methods and quoted or negotiated selling prices.</li>",
"<li>Buyer and customer lists, contact persons, order histories, sourcing calendars, buyer manuals, compliance audit reports and any terms specific to a buyer.</li>",
"<li>Supplier and vendor lists, sub-contractor lists, fabricator and job-worker details, procurement prices and credit terms negotiated with them.</li>",
"<li>Production schedules, capacity data, efficiency and productivity figures, defect and rejection data, and machinery configurations.</li>",
"<li>Financial information, including turnover, margins, banking arrangements, salary structures and any data forming part of the Company books of account.</li>",
"<li>Business strategies, marketing plans, expansion proposals, computer software, databases, passwords and any other information designated by management as confidential.</li>",
"</ul>",
"<h4>26.2 Obligations of the Employee</h4>",
"<p>Each employee shall, both during the term of employment and after its termination for any reason whatsoever, keep all Confidential Information secret and shall not, without the prior written consent of the Management.</p>",
"<ul>",
"<li>Disclose, communicate or make available any Confidential Information to any third party, including relatives, former colleagues, competitors, buyers or suppliers, except where disclosure is required in the proper performance of the employee duties.</li>",
"<li>Use any Confidential Information for any purpose other than the legitimate business of the Company.</li>",
"<li>Copy, photograph, reproduce, transmit, e-mail or remove from the Company premises any document, file, pattern, sample or electronic record containing Confidential Information, except as authorised in writing.</li>",
"<li>Discuss buyer prices, costing or order details with any person who does not have a clear need to know such information.</li>",
"</ul>",
"<p>The duty of confidentiality continues to bind the employee indefinitely and shall survive the cessation of employment. Resignation, retirement, termination or any other form of separation does not release the employee from this obligation.</p>",
"<h4>26.3 Intellectual Property &amp; Ownership of Work Product</h4>",
"<p>All designs, patterns, drawings, samples, inventions, improvements, processes, software, written material and other work product created, developed or contributed to by an employee during the course of employment, whether alone or jointly, and whether during or outside working hours where it relates to the business of the Company, shall be the sole and exclusive property of the Company. Where a design or product is developed for or on behalf of a buyer, the rights vest as agreed between the Company and that buyer. The employee hereby assigns, and agrees to assign, all such rights to the Company and shall, at the request and cost of the Company, execute any document and do any act necessary to perfect the Company title to such intellectual property. The employee waives any moral rights in such work to the extent permitted by law.</p>",
"<h4>26.4 Non-Solicitation</h4>",
"<p>During employment and for a period of twelve (12) months following separation, the employee shall not, directly or indirectly, solicit or entice away any buyer, customer, supplier, sub-contractor or employee of the Company with whom the employee had material dealings during the last twelve months of employment, where such solicitation is intended to cause loss or detriment to the Company.</p>",
"<h4>26.5 Return of Property on Exit</h4>",
"<p>Upon resignation, termination, retirement or at any time on the request of the Management, the employee shall immediately return to the Company all property in the employee possession or control, including all documents, patterns, samples, swatch cards, costing sheets, price lists, buyer correspondence, identity cards, access cards, laptops, mobile phones, SIM cards, storage media and any copies thereof in any form. No copies, extracts or summaries shall be retained by the employee. Clearance of these items forms part of the No-Dues process described in Chapter 33.</p>",
"<h4>26.6 Breach</h4>",
"<p>Any breach of this chapter shall constitute gross misconduct, exposing the employee to disciplinary action up to and including dismissal, and shall entitle the Company to seek injunctive relief, damages and recovery of any loss suffered, in addition to initiating criminal proceedings where the conduct so warrants under applicable law.</p>",

"<h3>27. Information Technology, Email, Data Protection &amp; Acceptable Use</h3>",
"<p>The Company provides computers, servers, the ERP system, e-mail accounts, internet connectivity, mobile devices, biometric attendance machines and related information technology resources to enable employees to perform their duties efficiently. These resources are provided for legitimate business purposes and remain at all times the property of the Company. This chapter sets out the rules governing their acceptable use.</p>",
"<h4>27.1 Authorised Use</h4>",
"<p>Company IT systems and devices shall be used primarily for business purposes. Limited, occasional and reasonable personal use of e-mail and the internet may be permitted at the discretion of the Management, provided it does not interfere with work, consume material Company resources, breach any policy or expose the Company to risk. Personal use is a privilege and not a right and may be withdrawn at any time.</p>",
"<h4>27.2 Passwords &amp; Access Security</h4>",
"<ul>",
"<li>Each user is responsible for the security of the user-ids and passwords issued to them. Passwords must be kept strictly confidential and must not be shared, written down in accessible places or disclosed to any other person, including IT staff.</li>",
"<li>Passwords must be of adequate strength and must be changed periodically as directed. Default passwords must be changed on first login.</li>",
"<li>Employees must lock or log off their workstation when leaving it unattended.</li>",
"<li>Any actual or suspected breach of security, loss of a device or compromise of a password must be reported to the IT in-charge or Management immediately.</li>",
"<li>Attempting to access systems, files, records or modules for which the employee has not been granted authorisation is strictly prohibited.</li>",
"</ul>",
"<h4>27.3 E-mail &amp; Communication</h4>",
"<p>Company e-mail accounts must be used for official correspondence. Employees must exercise the same care and courtesy in e-mail as in any other business communication. E-mail must not be used to send Confidential Information to personal accounts, to transmit offensive, defamatory, obscene or discriminatory material, or to create the impression that a personal view represents the view of the Company. Official records, buyer correspondence and orders must be transacted through Company systems and not through personal messaging applications or personal e-mail.</p>",
"<h4>27.4 Internet &amp; Prohibited Use</h4>",
"<p>The following uses of Company IT resources are expressly prohibited.</p>",
"<ul>",
"<li>Accessing, downloading, storing or distributing pornographic, obscene, defamatory, hateful or otherwise unlawful material.</li>",
"<li>Downloading or installing unlicensed, pirated or unauthorised software, or disabling antivirus or security tools.</li>",
"<li>Introducing viruses, malware or any harmful code, or knowingly opening suspicious attachments or links.</li>",
"<li>Using Company resources for any personal business, trading, gambling or for the benefit of a competitor.</li>",
"<li>Connecting unauthorised personal devices, external drives or modems to Company systems without permission.</li>",
"<li>Tampering with, copying or extracting data from the ERP, accounts or production databases without authority.</li>",
"</ul>",
"<h4>27.5 Data Protection</h4>",
"<p>The Company collects and processes personal data of employees, buyers and suppliers for legitimate business and statutory purposes. Employees who handle such data must keep it secure, use it only for the purpose for which it was collected, and not disclose it to unauthorised persons. The Company processes employee data in accordance with applicable law and retains it for the periods required by statutory obligations. Employees must promptly inform Human Resources of any change in their personal details so that records remain accurate.</p>",
"<h4>27.6 Monitoring</h4>",
"<p>Employees are advised that the Company reserves the right to monitor, log, inspect and review the use of its IT systems, including e-mail, internet usage, files stored on Company devices, ERP activity logs and biometric attendance records, to the extent permitted by law, for purposes of security, compliance, productivity and investigation of misconduct. Employees should have no expectation of privacy in respect of data created, stored or transmitted on Company systems. By using Company IT resources, employees consent to such monitoring.</p>",
"<h4>27.7 Software Licensing &amp; Backups</h4>",
"<p>Only software licensed to or approved by the Company may be installed. Critical business data must be stored on designated network locations or the ERP so that it is captured by the Company backup routine; data stored only on local drives or personal devices is at risk and is not the responsibility of the Company. Breach of this chapter constitutes misconduct and may attract disciplinary action.</p>",

"<h3>28. Company Assets, Tools, Machinery &amp; Materials</h3>",
"<p>The Company invests substantially in machinery, tools, equipment, fabric and trims to carry on the business of garment manufacturing. Every employee has a duty to protect these assets, to use them only for authorised purposes and to prevent loss, damage and wastage.</p>",
"<h4>28.1 Issue &amp; Custody of Assets</h4>",
"<p>Tools, instruments, scissors, measuring tapes, attachments, uniforms, identity cards, laptops, mobile phones, vehicles and other assets are issued to employees against acknowledgment. Where an asset is issued, the employee in whose custody it is placed is personally accountable for it. A record of issue shall be maintained by the concerned department or stores. Machinery such as sewing machines, cutting machines, fusing machines, boilers and generators is operated under the custody and supervision of the assigned operator and supervisor.</p>",
"<h4>28.2 Care &amp; Proper Use</h4>",
"<ul>",
"<li>Machines must be operated only by trained and authorised persons, strictly in accordance with operating instructions and safety guards in place.</li>",
"<li>Tools and equipment must be kept clean, maintained in good condition and used only for the purpose for which they are intended.</li>",
"<li>Fabric, trims, thread and other materials must be drawn against requisition, used economically and not wasted, and any surplus or off-cuts must be returned or accounted for as per the consumption norm.</li>",
"<li>Cut panels, work-in-progress and finished garments must be handled carefully to avoid soiling, staining or damage.</li>",
"<li>No Company asset or material shall be taken out of the premises without a proper gate pass authorised by the competent authority.</li>",
"<li>Any fault, breakdown, defect or safety hazard in machinery must be reported immediately to the supervisor; employees must not attempt unauthorised repairs.</li>",
"</ul>",
"<h4>28.3 Personal Use Prohibited</h4>",
"<p>Company tools, machinery, materials and vehicles must not be used for personal work, for private gain or for the benefit of any third party. Production of garments or articles for personal use or sale, using Company time, machinery or materials, is strictly prohibited and constitutes serious misconduct.</p>",
"<h4>28.4 Return of Assets</h4>",
"<p>All assets issued to an employee must be returned in good condition, subject to normal wear and tear, on transfer, on completion of the assignment, or on separation from service. The return of all assets is a precondition for No-Dues clearance and the release of the Full &amp; Final Settlement.</p>",
"<h4>28.5 Recovery for Loss or Damage</h4>",
"<p>Where any Company asset or material is lost, stolen, damaged or rendered unserviceable due to the negligence, carelessness, misuse or wilful default of an employee, the Company reserves the right, after due enquiry and subject to the limits prescribed under the Payment of Wages Act 1936, to recover the cost or a part thereof from the employee, in addition to taking disciplinary action. Loss arising from theft or wilful damage will additionally be treated as gross misconduct and may be referred to the police.</p>",

"<h3>29. Field Staff, Travel, Vehicle &amp; Expense Policy</h3>",
"<p>This chapter applies to the sales and marketing team and to any other employee who travels on Company business or works in the field, including sales executives, marketing officers, area and regional sales managers, collection and recovery staff, and merchandisers who visit buyers. Field staff represent the face of the Company and are entrusted with significant independence; with that independence comes a corresponding duty of honesty, diligence and accurate reporting.</p>",
"<h4>29.1 Route Plans &amp; Beat Coverage</h4>",
"<p>Field staff shall prepare and obtain approval for a tour programme or beat plan covering the dealers, distributors, retailers or buyers to be visited, together with the objective of each visit. Deviation from the approved route or programme requires the prior approval of the reporting manager, except in genuine emergencies which must be reported at the earliest opportunity.</p>",
"<h4>29.2 Daily Visit Reporting &amp; GPS</h4>",
"<ul>",
"<li>Field staff must record each customer visit in the Company ERP or the daily call report (DCR) on the same day, capturing the customer name, purpose, outcome, orders booked and follow-up actions.</li>",
"<li>Where the Company provides a mobile application with GPS-based check-in, field staff must mark their attendance and visit locations through the application. Switching off GPS, falsifying location, marking false visits or sharing the device with another person to mark attendance constitutes serious misconduct.</li>",
"<li>Targets, orders and collections will be reviewed against the daily and weekly reports submitted.</li>",
"</ul>",
"<h4>29.3 Collections &amp; Deposit of Cash</h4>",
"<p>Field staff who collect payments, cash or cheques on behalf of the Company hold such money in trust and as agent of the Company. The following rules are mandatory.</p>",
"<ul>",
"<li>An official receipt must be issued for every amount collected, and the collection must be entered in the system on the same day.</li>",
"<li>Cash collected must be deposited into the designated Company bank account or handed over to the cashier within the timeline prescribed by the Management (ordinarily by the next working day). Cheques must be deposited promptly and post-dated cheques recorded.</li>",
"<li>Collected money must never be used for personal purposes, for meeting travel expenses, or to set off against any dues. Any delay, shortfall or temporary use of collected funds will be treated as misappropriation and gross misconduct, and may lead to dismissal and criminal proceedings, in addition to recovery.</li>",
"<li>Outstanding statements must be reconciled periodically with the accounts department.</li>",
"</ul>",
"<h4>29.4 Travel &amp; Mileage Claims</h4>",
"<p>Field staff are entitled to reimbursement of actual and reasonable expenses incurred wholly for Company business, in accordance with the entitlement applicable to their grade. The following principles apply.</p>",
"<ul>",
"<li>Claims must be supported by original bills, tickets, receipts and, where relevant, the daily call report establishing the business purpose. Self-declared claims may be allowed only where the Company has fixed a standard rate.</li>",
"<li>Mileage for use of a personal two-wheeler or car will be reimbursed at the per-kilometre rate notified by the Company, based on the actual route and distance travelled. Inflated, duplicated or fictitious distances are prohibited.</li>",
"<li>Conveyance, lodging and daily allowance (DA) for outstation travel will be reimbursed within the ceilings notified for each grade. Stays exceeding the ceiling require prior sanction.</li>",
"<li>Claims must be submitted within the period prescribed (ordinarily within fifteen days of the expense being incurred). Claims submitted late may be disallowed.</li>",
"</ul>",
"<h4>29.5 Company Vehicles</h4>",
"<p>Where a Company vehicle or fuel card is provided, it shall be used solely for official purposes. The user shall hold a valid driving licence, comply with all traffic laws, maintain the vehicle log, and ensure the vehicle is serviced and insured as scheduled. Traffic fines arising from the user negligence and any private use of fuel are recoverable from the user. The user shall not permit any unauthorised person to drive the vehicle.</p>",
"<h4>29.6 Misuse as Misconduct</h4>",
"<p>Falsification of expense claims, submission of fake or inflated bills, false visit reporting, manipulation of GPS, misuse of the Company vehicle and delay or default in depositing collections are each treated as serious misconduct. Such conduct attracts disciplinary action up to and including dismissal, recovery of amounts involved and, where warranted, criminal complaint.</p>",

"<h3>30. Social Media &amp; External Communication</h3>",
"<p>The reputation and goodwill of __COMPANY__ are valuable assets. The widespread use of social media and instant messaging means that the actions of a single employee can affect the standing of the entire organisation, its buyers and its workforce. This chapter governs the conduct of employees on social media and in dealings with external parties, the press and the public.</p>",
"<h4>30.1 General Principles</h4>",
"<ul>",
"<li>Employees are personally responsible for what they post online. Where an employee can be identified as working for the Company, they must make clear that the views expressed are their own and not those of the Company.</li>",
"<li>Employees must not disclose any Confidential Information of the Company, its buyers or suppliers on any social media platform, blog, forum or messaging group. This includes photographs of designs, samples, factory floors, machinery, buyer labels, packing or shipment details.</li>",
"<li>Employees must not post any material that is defamatory, abusive, harassing, discriminatory or hateful towards the Company, its management, colleagues, buyers, suppliers or any other person.</li>",
"<li>Employees must not post content that damages or is likely to damage the reputation, brand or commercial interests of the Company.</li>",
"</ul>",
"<h4>30.2 Speaking on Behalf of the Company</h4>",
"<p>No employee, other than those expressly authorised in writing by the Management, may speak to or correspond with the press, media, trade bodies, government authorities or the public on behalf of the Company, or hold themselves out as a spokesperson of the Company. All media enquiries, public statements, press releases and interview requests must be referred to the authorised person. Employees must not give any commitment, quotation or assurance to a buyer or any external party beyond their delegated authority.</p>",
"<h4>30.3 Photography &amp; Recording on Premises</h4>",
"<p>Photography, video or audio recording inside the factory, design studio, sample room or stores is not permitted without prior authorisation, in order to protect designs, buyer property and the privacy of fellow workers.</p>",
"<h4>30.4 Consequences</h4>",
"<p>Breach of this chapter, whether the activity is conducted on Company time or personal time and whether on Company or personal devices, may amount to misconduct and attract disciplinary action proportionate to the seriousness of the breach, including dismissal in serious cases.</p>",

"<h3>31. Performance Management &amp; Appraisal</h3>",
"<p>The Company is committed to a culture of performance, fairness and continuous development. The performance management system is designed to align individual contribution with the goals of the organisation, to recognise and reward good performance, and to support employees who need to improve.</p>",
"<h4>31.1 The Appraisal Cycle</h4>",
"<p>The Company ordinarily follows an annual appraisal cycle aligned to the financial year (April to March). At the beginning of the cycle, each employee and the reporting manager agree the Key Result Areas (KRAs), objectives and measurable targets for the year. Mid-year reviews are conducted to track progress and recalibrate where necessary. The formal appraisal is conducted at the close of the cycle.</p>",
"<h4>31.2 KRAs &amp; Targets</h4>",
"<p>KRAs and targets are set having regard to the role of the employee. By way of illustration.</p>",
"<ul>",
"<li>For production and factory staff: output, efficiency, quality and right-first-time, adherence to delivery schedules, wastage control, attendance and safety compliance.</li>",
"<li>For sales and marketing staff: sales value and volume targets, new buyer acquisition, collection and outstanding control, market coverage and reporting discipline.</li>",
"<li>For merchandising and quality staff: on-time-in-full delivery, order execution accuracy, defect and rejection rates, buyer satisfaction and audit outcomes.</li>",
"<li>For support and management staff: functional deliverables, cost control, team development and process improvement.</li>",
"</ul>",
"<h4>31.3 Rating</h4>",
"<p>Performance is assessed against the agreed KRAs together with the demonstration of Company values and behaviours such as integrity, teamwork, discipline and ownership. Each employee is assigned an overall rating on the scale notified by the Company (for example, Outstanding, Exceeds Expectations, Meets Expectations, Needs Improvement and Unsatisfactory). Ratings are subject to a review and moderation process to ensure consistency and fairness across departments.</p>",
"<h4>31.4 Linkage to Increments &amp; Rewards</h4>",
"<p>Annual increments, performance incentives, bonuses (beyond statutory bonus), promotions and other rewards are linked to the appraisal rating, the financial performance of the Company and prevailing market conditions. The Company does not guarantee an increment in any year, and the quantum and timing of any increment are at the discretion of the Management.</p>",
"<h4>31.5 Performance Improvement Plan (PIP)</h4>",
"<p>Where an employee is rated as Needs Improvement or Unsatisfactory, or where performance falls materially short of the agreed standard, the employee may be placed on a Performance Improvement Plan. The PIP will specify the gaps identified, the specific and measurable improvement expected, the support and training to be provided, and a defined review period (ordinarily between one and three months). Progress will be reviewed at the close of the PIP. Sustained failure to meet the required standard despite a fair opportunity to improve may result in withholding of increment, change of role, or separation in accordance with this handbook and applicable law. The PIP is a developmental and corrective measure and is distinct from disciplinary action for misconduct.</p>",

"<h3>32. Promotions, Transfers, Deputation &amp; Training</h3>",
"<h4>32.1 Promotions</h4>",
"<p>Promotions are made on the basis of merit, demonstrated performance, potential, the availability of a suitable vacancy and the business needs of the Company. Seniority alone does not entitle an employee to promotion. A promotion may involve a change of designation, responsibilities, grade and compensation, and may be subject to a probationary or assessment period in the new role.</p>",
"<h4>32.2 Transfers, Deputation &amp; Inter-Unit Movement</h4>",
"<p>The services of every employee are liable to transfer or deputation to any department, section, unit, branch, factory, depot, sales territory or associated establishment of the Company, whether existing or to be set up in future, anywhere in India, as the exigencies of work may require. Such transfer may be to a similar or different role for which the employee is suited. On transfer, the employee will be governed by the rules and conditions applicable at the new location. Where a transfer involves relocation, applicable transfer benefits, if any, will be as notified by the Company. An employee directed to transfer must comply within the time stipulated; unjustified refusal to accept a lawful transfer is treated as misconduct.</p>",
"<h4>32.3 Deputation</h4>",
"<p>An employee may be placed on deputation to a buyer office, a sister concern, a vendor or for a special assignment, for a defined period, on terms communicated at the time of deputation. The lien on the parent position is ordinarily retained during deputation.</p>",
"<h4>32.4 Training &amp; Skill Development</h4>",
"<p>The Company recognises that a skilled workforce is essential to producing quality garments and to growing the business. The Company may provide, and employees are expected to participate fully in, training and skill development programmes, including the following.</p>",
"<ul>",
"<li>On-the-job training and skill upgradation for machine operators, tailors, cutting and finishing staff, including multi-skilling to improve flexibility and earning capacity.</li>",
"<li>Induction and orientation for new joiners.</li>",
"<li>Training on quality systems, buyer compliance, social and ethical standards, and workplace safety.</li>",
"<li>Sales and product training, ERP and IT systems training, and supervisory and managerial development for those identified for growth.</li>",
"</ul>",
"<p>Where the Company sponsors specialised or external training involving significant cost, the employee may be required to sign a service bond or undertaking to serve the Company for a minimum period thereafter, failing which the proportionate cost may be recovered, to the extent permitted by law.</p>",

"<h3>33. Separation from Service</h3>",
"<p>This chapter sets out the various modes by which the employment relationship may come to an end and the procedures applicable to each, together with the exit formalities. The provisions of this chapter operate subject to the terms of the individual appointment letter, the applicable standing orders, the Industrial Disputes Act 1947, the Payment of Gratuity Act 1972 and other applicable law.</p>",
"<h4>33.1 Resignation &amp; Notice Period</h4>",
"<p>An employee who wishes to resign must give written notice to the Management. The notice period is as stated in the appointment letter, and in the absence of a specified period, the following shall ordinarily apply: one month for confirmed employees in workman or operator categories and three months for staff in supervisory, executive and managerial categories. During probation, either party may terminate the engagement with the notice stated in the appointment letter, or such shorter period as may be specified. An employee may be permitted, at the sole discretion of the Management, to be relieved earlier by paying salary in lieu of the unserved notice; equally, the Company may relieve the employee earlier by paying salary in lieu. The employee shall continue to discharge duties diligently and shall complete a proper handover of charge, documents, samples and pending work during the notice period. Withdrawal of a resignation once accepted is permitted only with the written approval of the Management.</p>",
"<h4>33.2 Retirement</h4>",
"<p>The age of superannuation (retirement) is fifty-eight (58) years. An employee shall retire from the service of the Company on attaining this age, on the last day of the month in which the employee completes fifty-eight years, based on the date of birth recorded in the Company service records at the time of joining, which shall be conclusive for this purpose. The Company may, at its sole discretion and where business needs justify it, re-engage a retiring employee on a contractual or consultancy basis on terms to be mutually agreed; such re-engagement creates no right to continued regular employment.</p>",
"<h4>33.3 Termination &amp; Dismissal</h4>",
"<p>The Company may terminate the services of an employee in accordance with the appointment letter, the standing orders and applicable law. Termination for reasons other than misconduct (for example, on grounds of continued ill-health, loss of confidence in performance after due process, or on account of retrenchment) will be effected with the notice or pay in lieu and any compensation required by law, including, where applicable, the provisions of the Industrial Disputes Act 1947 relating to retrenchment. Dismissal as a penalty for proven misconduct will be effected only after a fair domestic enquiry conducted in accordance with the principles of natural justice and the disciplinary procedure set out in this handbook; in cases of dismissal for proven gross misconduct, the Company may dispense with notice and notice pay to the extent permitted by law.</p>",
"<h4>33.4 Abandonment of Service</h4>",
"<p>If an employee remains absent from duty without sanctioned leave and without intimation for a continuous period of eight (8) days or more, the employee shall be deemed to have no intention of continuing in service and to have voluntarily abandoned the employment. In such a case, the Company will issue notice to the last recorded address calling upon the employee to report for duty and explain the absence within a stipulated time. If the employee fails to report or to give a satisfactory explanation within the time allowed, the name of the employee may be struck off the rolls and the employment treated as terminated on account of abandonment, after following the procedure required under the applicable standing orders.</p>",
"<h4>33.5 No-Dues Clearance</h4>",
"<p>On separation by any mode, the employee must obtain clearance from all concerned departments through the No-Dues form. This includes the return of all Company assets and Confidential Information (Chapters 26 and 28), settlement of advances, loans, tour expenses and collections, clearance of stores, IT assets, identity and access cards, and confirmation from accounts. The release of the Full &amp; Final Settlement and of the relieving documents is contingent upon completion of the No-Dues clearance.</p>",
"<h4>33.6 Full &amp; Final Settlement</h4>",
"<p>The Full &amp; Final Settlement (F&amp;F) will be computed and paid within the timeline prescribed by the Management after the last working day and after completion of No-Dues clearance, ordinarily within forty-five (45) days. The settlement will include salary due up to the last working day, encashment of eligible leave as per the leave policy, statutory bonus if due, and gratuity where the employee has completed the qualifying continuous service of five years under the Payment of Gratuity Act 1972 (the five-year condition being relaxed in the case of death or disablement as provided in that Act). From the amounts payable, the Company will deduct any recoveries lawfully due, including unserved notice period, outstanding advances and loans, dues for loss or damage to Company property determined after enquiry, and any other statutory or contractual dues. Settlement of Provident Fund and Employees State Insurance, where applicable, will be processed through the respective statutory authorities.</p>",
"<h4>33.7 Relieving &amp; Experience Certificate</h4>",
"<p>Upon satisfactory completion of the notice period, handover and No-Dues clearance, the Company will issue a relieving letter and, on request, an experience or service certificate stating the period of service and the last designation held. The Company is under no obligation to comment on the conduct or performance of the employee in such certificate.</p>",
"<h4>33.8 Exit Interview</h4>",
"<p>Departing employees are ordinarily requested to participate in an exit interview with Human Resources. The purpose of the exit interview is to understand the reasons for separation, to obtain candid feedback on the work environment and to identify areas for improvement. Participation is encouraged, and the information shared will be treated with appropriate confidentiality and used constructively.</p>",

"<h3>34. General Provisions</h3>",
"<h4>34.1 Amendment of Policies</h4>",
"<p>The Company reserves the right to add to, amend, modify, supplement, withdraw or replace any policy, rule, benefit or provision contained in this handbook, in whole or in part, at any time, as it deems appropriate in the interest of the business and to comply with changes in law. Such changes will be notified by display on the notice board, by circular, by e-mail or through the ERP, and will take effect from the date specified. The handbook does not constitute a contract of employment or a guarantee of any particular benefit, and in the event of any conflict between this handbook and the individual appointment letter or applicable law, the appointment letter and the law shall prevail to the extent of the conflict.</p>",
"<h4>34.2 Interpretation</h4>",
"<p>In case of any doubt, dispute or difference regarding the meaning, interpretation or application of any provision of this handbook, the decision of the Management shall be final and binding. Words importing the singular include the plural and vice versa, and words importing one gender include the other gender.</p>",
"<h4>34.3 Severability</h4>",
"<p>If any provision of this handbook is held to be invalid, illegal or unenforceable under any applicable law, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired, and the invalid provision shall be deemed modified to the minimum extent necessary to make it valid and enforceable.</p>",
"<h4>34.4 Governing Law &amp; Jurisdiction</h4>",
"<p>This handbook and the employment relationship shall be governed by and construed in accordance with the laws of India. Subject to any statutory dispute-resolution mechanism applicable to industrial disputes, the courts and tribunals having jurisdiction over the place where the registered office or the concerned establishment of the Company is situated shall have exclusive jurisdiction in respect of any matter arising out of or in connection with this handbook.</p>",
"<h4>34.5 Welfare Amenities</h4>",
"<p>In keeping with its obligations under the Factories Act 1948 and other applicable welfare legislation, the Company provides welfare amenities for the benefit of its workforce. These ordinarily include the following, commensurate with the strength of the workforce and the requirements of law.</p>",
"<ul>",
"<li>Wholesome drinking water at convenient and marked points, kept clean and, where required, cooled during the hot season.</li>",
"<li>Sufficient and separate latrines and urinals for male and female workers, maintained in a clean and sanitary condition.</li>",
"<li>Washing facilities and, where applicable, facilities for storing and drying clothing.</li>",
"<li>A canteen or refreshment facility where the number of workers so requires, providing food and beverages on a no-profit basis, and clean spaces for taking meals.</li>",
"<li>Rest rooms or shelters, and a creche facility where the number of women workers so requires, for the care of young children.</li>",
"<li>A first-aid box at accessible points and an ambulance room or arrangement where required by law.</li>",
"<li>Adequate lighting, ventilation, cleanliness and sanitation throughout the premises.</li>",
"</ul>",
"<p>Employees are expected to use these amenities responsibly, to keep them clean and to report any deficiency to the supervisor or the welfare officer so that it can be promptly addressed.</p>",

"<h3>35. Declaration &amp; Acknowledgment by Employee</h3>",
"<p>I hereby declare and acknowledge that I have received a copy of the Employee Policy Handbook of __COMPANY__. I confirm that I have read and understood its contents, or that the same have been read out and explained to me in a language I understand. I agree to abide by and be bound by all the policies, rules, terms and conditions set out in this handbook, as amended from time to time, throughout the period of my employment. I understand that this handbook is intended for guidance, that the Company may amend its provisions, and that nothing in this handbook constitutes a guarantee of employment for any fixed term. I further acknowledge that my obligations of confidentiality, non-disclosure and protection of the Company intellectual property survive the termination of my employment. I undertake to conduct myself with integrity and discipline and to uphold the values and reputation of the Company at all times.</p>",
"<table style='width:100%;border-collapse:collapse;margin-top:16px;'>",
"<tr>",
"<td style='width:55%;vertical-align:top;border:1px solid #333;padding:14px;'>",
"<p style='margin:0 0 10px 0;'><strong>Acknowledged by Employee</strong></p>",
"<p style='margin:0 0 12px 0;'>Name: ______________________________</p>",
"<p style='margin:0 0 12px 0;'>Employee Code: ______________________</p>",
"<p style='margin:0 0 12px 0;'>Department / Designation: _____________</p>",
"<p style='margin:0 0 12px 0;'>Signature: __________________________</p>",
"<p style='margin:0;'>Date: _______________________________</p>",
"</td>",
"<td style='width:45%;vertical-align:top;border:1px solid #333;padding:14px;'>",
"<p style='margin:0 0 28px 0;'><strong>For __COMPANY__</strong></p>",
"<p style='border-top:1px solid #333;padding-top:8px;margin:0 0 10px 0;'>Authorised Signatory</p>",
"<p style='margin:0 0 12px 0;'>Name: ______________________________</p>",
"<p style='margin:0 0 12px 0;'>Designation: ________________________</p>",
"<p style='margin:0;'>Date &amp; Seal: ________________________</p>",
"</td>",
"</tr>",
"</table>"
].join("");
