module.exports = [
"<h3>18. Code of Conduct &amp; Business Ethics</h3>",
"<p>__COMPANY__ operates in a competitive global garment market where our reputation rests on two pillars: the quality of what we make and the integrity of how we make it. Every person who works at __COMPANY__ &mdash; whether stitching a seam on the production floor, negotiating with a buyer, sourcing fabric, or signing a cheque &mdash; carries the name of the Company. This chapter sets out the standards of personal and professional conduct expected of all employees, workers, trainees, apprentices, contract personnel and management staff (collectively, &lsquo;employees&rsquo; in this Handbook). These standards apply on Company premises, at customer and supplier sites, during travel on Company business, at off-site events, and on any occasion where an employee can reasonably be identified with __COMPANY__.</p>",
"<p>The Code of Conduct is not a list of suggestions. It is a binding condition of employment, read together with the Company&rsquo;s Certified Standing Orders framed under the Industrial Employment (Standing Orders) Act, 1946, and with the statutory obligations imposed by the Factories Act, 1948, the Industrial Disputes Act, 1947, and the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013. Where any provision of this Handbook conflicts with a statute or with the Certified Standing Orders, the statute or the Certified Standing Orders shall prevail, but in all other respects this Handbook supplements and explains the standards we expect.</p>",
"<h4>18.1 Core Values</h4>",
"<p>The conduct of every employee should reflect five core values that define __COMPANY__:</p>",
"<ul>",
"<li><strong>Integrity</strong> &mdash; We are honest in our work, our records and our dealings. We do not steal, cheat, lie, or falsify. We do not take what does not belong to us, whether it is a metre of fabric, an hour of paid time, or credit for another person&rsquo;s work.</li>",
"<li><strong>Respect</strong> &mdash; We treat every colleague, supervisor, subordinate, visitor, buyer and supplier with courtesy and dignity, regardless of gender, religion, caste, region, language, age, disability or position in the Company.</li>",
"<li><strong>Discipline</strong> &mdash; We follow lawful instructions, observe working hours, obey safety rules, and conduct ourselves in an orderly manner so that the factory runs smoothly and safely.</li>",
"<li><strong>Responsibility</strong> &mdash; We take ownership of our tasks, our machines, our materials and our mistakes. We do not pass blame or hide problems.</li>",
"<li><strong>Safety</strong> &mdash; We protect ourselves and others. No order, no deadline and no production target ever justifies an unsafe act.</li>",
"</ul>",
"<h4>18.2 Punctuality &amp; Attendance</h4>",
"<p>A garment factory works as a connected line. When one operator is late or absent, the whole line slows, downstream sections starve, and delivery commitments to buyers are put at risk. Every employee shall report to their workstation, in proper attire and ready to work, before the scheduled start of the shift, and shall remain at work until the shift ends, except during authorised breaks. Employees must record their attendance through the prescribed biometric or card system; punching another person&rsquo;s attendance, or asking someone to punch yours, is a serious act of misconduct (see Chapter 19). Leaving the workstation or the factory premises during working hours requires the permission of the immediate supervisor and the recording of a gate pass.</p>",
"<h4>18.3 Sobriety</h4>",
"<p>Employees shall report for duty in a fit physical and mental condition. Reporting to work, or being on Company premises, under the influence of alcohol, narcotics or any intoxicating or psychotropic substance is strictly prohibited and is treated as major misconduct. Consumption, possession, sale or distribution of alcohol or prohibited substances anywhere on Company premises is forbidden. In a factory full of moving machinery, needles, cutters, boilers and electrical equipment, an intoxicated worker is a danger to everyone. The Company may require an employee reasonably suspected of intoxication to undergo a medical examination; refusal may itself be treated as misconduct.</p>",
"<h4>18.4 Respectful Workplace</h4>",
"<p>__COMPANY__ is committed to a workplace free from harassment, bullying, intimidation, abusive language, casteist or communal slurs, and any form of discrimination. Supervisors and managers hold authority to direct work, but that authority must always be exercised with respect and never as a licence to humiliate, threaten or physically handle a worker. Use of physical force, abusive shouting, or threats by anyone &mdash; including a supervisor against a worker &mdash; is misconduct. Detailed protection against sexual harassment is set out in Chapter 22.</p>",
"<h4>18.5 Conflict of Interest</h4>",
"<p>A conflict of interest arises when an employee&rsquo;s personal interest interferes, or appears to interfere, with the interest of __COMPANY__. Employees must avoid situations where their judgement on behalf of the Company could be influenced by personal gain. The following must be disclosed in writing to the Human Resources department and, where required, approved in advance:</p>",
"<ul>",
"<li>Any financial interest in, or employment with, a supplier, sub-contractor, job-worker, buyer, transporter or competitor of __COMPANY__.</li>",
"<li>The engagement of a close relative as a supplier, contractor or service provider to the Company, or the recruitment, supervision or evaluation of a close relative within the Company.</li>",
"<li>Any outside business, trade or paid employment that an employee carries on while employed by __COMPANY__, particularly if it relates to garments, textiles or any line of the Company&rsquo;s business.</li>",
"<li>Acceptance of any personal benefit, commission, loan or favour from a party that does business, or seeks to do business, with the Company.</li>",
"</ul>",
"<p>An employee must never use their position, the Company&rsquo;s name, its assets, or confidential information for personal profit or for the benefit of a third party. Diverting a Company order, sample, design or buyer contact to a personal venture or to an outsider is a grave breach of trust.</p>",
"<h4>18.6 Gifts, Hospitality &amp; Entertainment</h4>",
"<p>Employees, particularly those in purchasing, merchandising, sampling, quality, stores, security and accounts, regularly deal with parties who may seek to influence decisions through gifts. The rule is one of moderation and transparency:</p>",
"<ul>",
"<li>Employees shall not solicit gifts, cash, gift cards, or favours from any supplier, buyer, contractor, inspector or other business contact.</li>",
"<li>Unsolicited gifts of token value (such as a diary, calendar, sweets at a festival, or a pen) given openly may be accepted but should be shared with the team where practical.</li>",
"<li>Gifts of cash or cash-equivalents must never be accepted in any amount.</li>",
"<li>Any gift, hospitality or offer that exceeds nominal value, or that could reasonably be seen as intended to influence a business decision, must be politely declined and reported to the reporting manager and Human Resources.</li>",
"<li>Lavish entertainment, paid holidays, or personal services from a business contact must be declined.</li>",
"</ul>",
"<p>The detailed anti-bribery framework is set out in Chapter 25 and must be read together with this section.</p>",
"<h4>18.7 Confidentiality &amp; Protection of Company Information</h4>",
"<p>In the course of work, employees gain access to information that is valuable and confidential: buyer designs, tech-packs, patterns, costings, price lists, production methods, supplier terms, customer lists, payroll data and the personal data of fellow employees. All such information is the property of __COMPANY__ or of its customers and must be protected. Employees shall not copy, photograph, remove, share or disclose confidential information except as required for their work and authorised by management. The unauthorised photography of designs, samples, production lines or documents using mobile phones or cameras is prohibited. The obligation of confidentiality continues even after an employee leaves the Company.</p>",
"<h4>18.8 Use of Company Property &amp; Resources</h4>",
"<p>Machines, tools, vehicles, computers, materials, electricity, water and time paid for by the Company are to be used for Company purposes. Employees must take reasonable care of all property entrusted to them and report any loss, damage or malfunction promptly. Wilful or negligent damage, misuse, or unauthorised personal use of Company property is misconduct.</p>",
"<h4>18.9 Statements to Media &amp; Public</h4>",
"<p>No employee may make any statement to the press, broadcast or online media, or post on social media, in a manner that purports to represent __COMPANY__ or that brings the Company, its buyers or its employees into disrepute. Authority to speak for the Company rests solely with persons designated by management.</p>",

"<h3>19. Standing Orders &mdash; Schedule of Acts of Misconduct</h3>",
"<p>The following Schedule is framed in keeping with the Model Standing Orders under the Industrial Employment (Standing Orders) Act, 1946, and forms part of the conditions of service at __COMPANY__. The acts listed below are illustrative, not exhaustive: conduct of a similar nature, or any conduct that a reasonable person would recognise as a breach of the duties owed to the Company, may also be treated as misconduct even if not specifically named here. Misconduct is broadly classified as <strong>minor misconduct</strong> and <strong>major (grave) misconduct</strong>. Major misconduct, when proved through the disciplinary procedure set out in Chapter 20, may attract penalties up to and including dismissal from service.</p>",
"<h4>19.1 Schedule of Acts and Omissions Constituting Misconduct</h4>",
"<ol>",
"<li><strong>Theft, fraud or dishonesty</strong> in connection with the Company&rsquo;s business or property, or the property of any other employee, buyer, supplier or visitor on the premises &mdash; including theft or pilferage of fabric, trims, accessories, finished garments, tools, scrap or waste.</li>",
"<li><strong>Misappropriation</strong> or unauthorised removal of cash, materials, samples, documents or any other Company property.</li>",
"<li><strong>Falsification, tampering with, or unauthorised alteration</strong> of any Company record, including attendance, gate passes, production records, quality reports, inspection reports, vouchers, registers, certificates and muster rolls.</li>",
"<li><strong>Punching, signing or recording the attendance</strong> of another employee, or causing or permitting one&rsquo;s own attendance to be so recorded by another.</li>",
"<li><strong>Bribery, acceptance or demand of illegal gratification</strong>, commission, kickback or any improper benefit from a supplier, buyer, contractor, inspector, fellow employee or any other person in connection with the Company&rsquo;s business.</li>",
"<li><strong>Wilful insubordination or disobedience</strong>, whether alone or with others, of any lawful and reasonable order of a superior.</li>",
"<li><strong>Riotous, disorderly or indecent behaviour</strong>, fighting, assault, or use of abusive, threatening or intimidating language on the premises or in connection with work.</li>",
"<li><strong>Habitual late attendance</strong>, or habitual absence without leave or without sufficient cause, or overstaying sanctioned leave without prior intimation.</li>",
"<li><strong>Absence from the appointed place of work</strong> without permission, or leaving work before the end of the shift without authorisation.</li>",
"<li><strong>Habitual negligence or neglect of work</strong>; careless, slow or wilfully bad workmanship; or repeated failure to meet reasonable quality or output standards.</li>",
"<li><strong>Negligence or carelessness causing damage</strong> to Company property, machinery, materials or goods, or causing loss to the Company or to any person.</li>",
"<li><strong>Sabotage</strong> &mdash; wilful damage to, or wilful interference with, machinery, equipment, materials, finished goods, records or the production process; or deliberate go-slow.</li>",
"<li><strong>Sleeping while on duty.</strong></li>",
"<li><strong>Gambling, betting or playing games of chance</strong> for money on the premises.</li>",
"<li><strong>Reporting for duty, or being on the premises, in a state of intoxication</strong>, or consuming, possessing, distributing or selling alcohol, narcotics or other intoxicating or prohibited substances on the premises.</li>",
"<li><strong>Breach of any safety rule</strong>, including failure to use, or interference with, any safety device, guard, fence or protective equipment provided; smoking in non-smoking or hazardous areas; and any act endangering the safety of oneself or others (see Chapter 23).</li>",
"<li><strong>Unauthorised operation, repair or interference with machinery, electrical equipment, boilers, lifts or any plant</strong> that one is not authorised or trained to operate; tampering with, removing or by-passing a machine guard or safety interlock.</li>",
"<li><strong>Sexual harassment</strong> of any person in the workplace, in the manner defined in Chapter 22 and under the POSH Act, 2013.</li>",
"<li><strong>Conduct that constitutes a conflict of interest</strong> as described in Chapter 18, including carrying on a competing business or diverting Company orders, designs or contacts.</li>",
"<li><strong>Unauthorised disclosure of confidential information</strong>, including buyer designs, tech-packs, costings, price lists and the personal data of employees.</li>",
"<li><strong>Unauthorised photography or recording</strong> of designs, samples, production processes or documents.</li>",
"<li><strong>Collection of money, canvassing, or unauthorised meetings</strong> within the premises during working hours without permission; engaging in any unauthorised trade or money-lending on the premises.</li>",
"<li><strong>Distribution or display of inflammatory, defamatory or unauthorised notices, posters or matter</strong>, or writing on walls, machines or property of the Company.</li>",
"<li><strong>Giving false information</strong> regarding name, age, qualification, experience, previous employment, identity or family particulars at the time of recruitment or thereafter.</li>",
"<li><strong>Refusal to accept or receive a charge-sheet, notice, order or other communication</strong> issued by the management.</li>",
"<li><strong>Abetment of, or attempt at, any of the above acts</strong>, and conviction by a court of law for any criminal offence involving moral turpitude.</li>",
"</ol>",
"<h4>19.2 Classification of Misconduct and Indicative Penalties</h4>",
"<p>The classification below is indicative. The actual penalty in any case shall be decided through the disciplinary procedure in Chapter 20, after considering the gravity of the act, the circumstances, the past record of the employee, and the principles of proportionality and natural justice. The Company may impose a lesser penalty than the indicative one where mitigating circumstances exist.</p>",
"<table style='border-collapse:collapse;width:100%;border:1px solid #333;'>",
"<thead><tr style='background:#dce6f1;'>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Category</th>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Nature / Examples</th>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Indicative Penalty</th>",
"</tr></thead>",
"<tbody>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Minor misconduct (first instance)</td>",
"<td style='border:1px solid #333;padding:6px;'>Occasional late attendance; minor untidiness; minor negligence not causing damage; first-time breach of a non-critical procedure.</td>",
"<td style='border:1px solid #333;padding:6px;'>Counselling or oral warning recorded in the personnel file.</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Minor misconduct (repeated)</td>",
"<td style='border:1px solid #333;padding:6px;'>Repeated lateness; repeated minor negligence; failure to follow instructions on housekeeping or 5S; absence without leave for a short period.</td>",
"<td style='border:1px solid #333;padding:6px;'>Written warning; in case of further repetition, fine as permitted by law, or withholding of increment.</td>",
"</tr>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Serious misconduct</td>",
"<td style='border:1px solid #333;padding:6px;'>Habitual absence or lateness; habitual negligence; insubordination; negligence causing damage; disorderly behaviour; sleeping on duty; gambling on premises.</td>",
"<td style='border:1px solid #333;padding:6px;'>Stoppage / withholding of increment; demotion; suspension without pay for up to four days; in repeated or aggravated cases, dismissal.</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Major / grave misconduct</td>",
"<td style='border:1px solid #333;padding:6px;'>Theft, fraud, misappropriation; falsification of records; bribery; sabotage; assault or fighting; intoxication on duty; serious breach of safety rules; sexual harassment; unauthorised use of machinery causing or risking injury; wilful damage; conviction for an offence involving moral turpitude.</td>",
"<td style='border:1px solid #333;padding:6px;'>Dismissal from service, with or without notice as permitted by law; recovery of loss; and, where the act is a cognisable offence, reference to the police.</td>",
"</tr>",
"</tbody>",
"</table>",
"<p>Where any penalty involves the imposition of a fine, the fine shall be imposed only in accordance with the limits and conditions prescribed under the Payment of Wages Act, 1936. No deduction by way of fine shall be made except for an act or omission notified as such, and the total amount of fine in any wage period shall not exceed the statutory ceiling.</p>",

"<h3>20. Disciplinary Procedure</h3>",
"<p>The purpose of discipline at __COMPANY__ is to correct behaviour and protect the workplace, not to punish for its own sake. The Company believes in a graded, fair and consistent approach. No employee shall be punished for misconduct without being given a fair opportunity to explain, in accordance with the principles of natural justice. Nothing in this chapter shall be construed to limit the rights of either the Company or the employee under the Industrial Disputes Act, 1947, the Certified Standing Orders, or any other applicable law.</p>",
"<h4>20.1 Counselling and Corrective Coaching</h4>",
"<p>For minor lapses, the first step is informal counselling by the immediate supervisor or Human Resources. The objective is to make the employee aware of the lapse, understand the reason, and agree on corrective action. Counselling is not a punishment but a corrective measure; a brief note may be placed in the personnel file recording that counselling took place.</p>",
"<h4>20.2 Verbal and Written Warnings</h4>",
"<p>If a lapse is repeated, or is somewhat more serious, the employee may be issued a verbal warning (recorded in the file) and, on further repetition, a written warning. A written warning shall specify the lapse, refer to any earlier counselling or warnings, and inform the employee that continued or repeated misconduct may lead to more serious disciplinary action. The employee is entitled to submit a written response to a warning.</p>",
"<h4>20.3 Show-Cause Notice</h4>",
"<p>Where misconduct is more serious, or where warnings have not produced improvement, the Company may issue a show-cause notice calling upon the employee to explain in writing, within a stated period (ordinarily not less than 48 hours), why disciplinary action should not be taken. The employee&rsquo;s explanation shall be considered before any further step is decided.</p>",
"<h4>20.4 Charge-Sheet</h4>",
"<p>For acts amounting to major or grave misconduct, a formal charge-sheet shall be issued. The charge-sheet shall:</p>",
"<ul>",
"<li>State clearly and specifically each act of misconduct alleged, with relevant dates, times, places and the Standing Order provision or Handbook clause said to have been breached;</li>",
"<li>Call upon the employee to submit a written explanation within a specified, reasonable time (ordinarily 48 to 72 hours); and</li>",
"<li>Be delivered to the employee personally against acknowledgement, or, if the employee refuses or is absent, sent by registered post to the last recorded address and/or affixed on the notice board, so that proper service is established.</li>",
"</ul>",
"<p>Refusal to accept a charge-sheet does not stop the proceedings; the Company shall record the refusal and proceed as though the charge-sheet had been served.</p>",
"<h4>20.5 Consideration of Explanation</h4>",
"<p>On receiving the employee&rsquo;s explanation, the disciplinary authority shall consider it. If the explanation is satisfactory, the matter may be dropped or closed with a warning, and the employee shall be informed. If the explanation is unsatisfactory, or if no explanation is received within the stipulated time, the Company may proceed to hold a domestic enquiry.</p>",
"<h4>20.6 Domestic Enquiry and Principles of Natural Justice</h4>",
"<p>A domestic enquiry is an internal fact-finding proceeding to determine whether the charges are proved. It shall be conducted in accordance with the principles of natural justice, which require:</p>",
"<ul>",
"<li><strong>Notice of enquiry</strong> &mdash; The employee shall be informed in writing of the date, time and place of the enquiry, with reasonable notice.</li>",
"<li><strong>An impartial Enquiry Officer</strong> &mdash; The enquiry shall be conducted by a person who has not been a witness to, or otherwise involved in, the incident, and who has no personal interest in the outcome.</li>",
"<li><strong>Opportunity to be heard</strong> &mdash; The employee shall be allowed to be present throughout, to hear the evidence led against them, to cross-examine the Company&rsquo;s witnesses, to produce their own witnesses and documents, and to make their submissions.</li>",
"<li><strong>Assistance</strong> &mdash; The employee may, in accordance with the Standing Orders, be assisted by a co-worker or, where applicable, a representative of a recognised union.</li>",
"<li><strong>Language</strong> &mdash; Proceedings shall, as far as practicable, be conducted in a language the employee understands, with translation provided where necessary.</li>",
"<li><strong>Record</strong> &mdash; A written record of the proceedings, evidence and statements shall be maintained and the employee&rsquo;s signature obtained on the daily record.</li>",
"<li><strong>Findings on evidence</strong> &mdash; The Enquiry Officer shall record findings on each charge, based only on the evidence on record, and shall not be influenced by extraneous matters.</li>",
"</ul>",
"<p>The standard of proof in a domestic enquiry is preponderance of probability, not the higher criminal standard of proof beyond reasonable doubt. Ex-parte enquiry may proceed only where the employee, after due notice, deliberately refuses or fails to participate without sufficient cause.</p>",
"<h4>20.7 Suspension Pending Enquiry</h4>",
"<p>Where the alleged misconduct is grave, or where the continued presence of the employee may hamper the enquiry, intimidate witnesses, or endanger persons or property, the Company may suspend the employee pending enquiry. During such suspension the employee shall be paid a subsistence allowance at the rate and for the periods prescribed by the applicable law and Standing Orders. Suspension pending enquiry is not itself a punishment; if the employee is fully exonerated, the period shall be treated as on duty and the balance of wages paid.</p>",
"<h4>20.8 Decision and Punishment</h4>",
"<p>On receipt of the Enquiry Officer&rsquo;s report, the disciplinary authority shall furnish a copy of the findings to the employee and give an opportunity to make a representation against the proposed punishment where required. The disciplinary authority shall then decide the punishment, having regard to the gravity of the proved misconduct, the past record of the employee, any mitigating or aggravating circumstances, and the principle of proportionality. Punishments may include, in ascending order of severity:</p>",
"<ol>",
"<li>Recorded warning or censure;</li>",
"<li>Fine, within the limits of the Payment of Wages Act, 1936;</li>",
"<li>Withholding or stoppage of increment, with or without cumulative effect;</li>",
"<li>Suspension without wages for a specified period within the limits of the Standing Orders;</li>",
"<li>Demotion to a lower post or grade;</li>",
"<li>Discharge from service; or</li>",
"<li>Dismissal from service, with or without notice, as permitted by law.</li>",
"</ol>",
"<p>The order of punishment shall be communicated to the employee in writing and shall record the charges, the findings and the reasons. The Company shall maintain documentation of the entire proceeding.</p>",
"<h4>20.9 Appeal</h4>",
"<p>An employee aggrieved by an order of punishment may, within a reasonable period (ordinarily seven working days of receiving the order), prefer a written appeal to the appellate authority designated by the Company. The appellate authority shall consider the appeal and may confirm, reduce, enhance (after notice), or set aside the punishment. The decision on appeal shall be communicated in writing. These internal remedies are without prejudice to the employee&rsquo;s statutory rights under the Industrial Disputes Act, 1947.</p>",

"<h3>21. Grievance Redressal Procedure</h3>",
"<p>__COMPANY__ recognises that the prompt and fair settlement of grievances is essential to industrial harmony and to the dignity of every employee. A grievance is any dissatisfaction or sense of injustice felt by an employee in connection with their employment &mdash; for example, regarding wages, allowances, leave, working conditions, work assignment, transfer, the behaviour of a supervisor or colleague, or the application of any rule or policy. Matters of sexual harassment are dealt with separately under Chapter 22, and matters of discipline are dealt with under Chapter 20.</p>",
"<h4>21.1 Principles</h4>",
"<ul>",
"<li>Every grievance shall be addressed promptly, fairly and without victimisation of the complainant.</li>",
"<li>An employee may raise a grievance without fear of retaliation; raising a genuine grievance shall never be treated as misconduct.</li>",
"<li>Grievances shall be dealt with at the lowest possible level and escalated only if not resolved.</li>",
"<li>Confidentiality shall be maintained to the extent practicable.</li>",
"</ul>",
"<h4>21.2 Stages and Timelines</h4>",
"<p>The grievance procedure follows a staged escalation, each stage with a defined time limit so that no grievance is left unattended:</p>",
"<table style='border-collapse:collapse;width:100%;border:1px solid #333;'>",
"<thead><tr style='background:#dce6f1;'>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Stage</th>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>To whom raised</th>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Time to respond</th>",
"</tr></thead>",
"<tbody>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Stage 1</td>",
"<td style='border:1px solid #333;padding:6px;'>Immediate supervisor / line in-charge (orally or in writing)</td>",
"<td style='border:1px solid #333;padding:6px;'>Within 2 working days</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Stage 2</td>",
"<td style='border:1px solid #333;padding:6px;'>Departmental Head / Production Manager (in writing, if Stage 1 unresolved)</td>",
"<td style='border:1px solid #333;padding:6px;'>Within 5 working days</td>",
"</tr>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Stage 3</td>",
"<td style='border:1px solid #333;padding:6px;'>Grievance Redressal Committee through Human Resources</td>",
"<td style='border:1px solid #333;padding:6px;'>Within 7 working days of reference</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Stage 4</td>",
"<td style='border:1px solid #333;padding:6px;'>Occupier / Senior Management for final decision</td>",
"<td style='border:1px solid #333;padding:6px;'>Within 7 working days</td>",
"</tr>",
"</tbody>",
"</table>",
"<h4>21.3 Grievance Redressal Committee</h4>",
"<p>The Company shall constitute a Grievance Redressal Committee comprising representatives of management and of the workmen, with adequate representation of women employees. The Committee shall meet as required to hear grievances referred to it, shall give the aggrieved employee an opportunity to be heard, and shall record its recommendations. The composition, quorum and procedure of the Committee shall conform to the requirements of the applicable law, including the grievance-redressal provisions of the Industrial Disputes Act, 1947.</p>",
"<h4>21.4 Records and Review</h4>",
"<p>Human Resources shall maintain a register of grievances recording the date received, nature, stages, outcome and time taken. Management shall periodically review grievance trends to identify and correct systemic causes. Where a grievance reveals a wider problem &mdash; for example, a recurring machine fault, an unfair work allocation, or an abusive supervisor &mdash; corrective action shall be taken at the systemic level and not merely for the individual case.</p>",

"<h3>22. Prevention of Sexual Harassment (POSH)</h3>",
"<p>__COMPANY__ is firmly committed to providing a safe working environment, free from sexual harassment, to every woman who works on its premises &mdash; whether as a regular employee, contract worker, trainee, apprentice, probationer, daily-wager or visitor. This policy is framed in accordance with the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 (the &lsquo;POSH Act&rsquo;) and the rules made under it. Sexual harassment is a violation of the fundamental rights of a woman to equality and to a life of dignity, and it will not be tolerated in any form at __COMPANY__.</p>",
"<h4>22.1 Definition of Sexual Harassment</h4>",
"<p>Sexual harassment includes any one or more of the following unwelcome acts or behaviour, whether directly or by implication:</p>",
"<ul>",
"<li>Physical contact and advances;</li>",
"<li>A demand or request for sexual favours;</li>",
"<li>Making sexually coloured remarks;</li>",
"<li>Showing pornography; and</li>",
"<li>Any other unwelcome physical, verbal or non-verbal conduct of a sexual nature.</li>",
"</ul>",
"<p>The following circumstances, among others, if they occur or are present in relation to or connected with any act or behaviour of sexual harassment, may amount to sexual harassment: an implied or explicit promise of preferential treatment in employment; an implied or explicit threat of detrimental treatment in employment; an implied or explicit threat about present or future employment status; interference with work or the creation of an intimidating, offensive or hostile work environment; and humiliating treatment likely to affect health or safety.</p>",
"<h4>22.2 Workplace</h4>",
"<p>For the purpose of this policy, &lsquo;workplace&rsquo; includes the entire factory premises, offices, stores, godowns, canteen, transport provided by the Company, and any place visited by an employee arising out of or during the course of employment, including on official travel.</p>",
"<h4>22.3 Internal Committee (IC)</h4>",
"<p>The Company has constituted an Internal Committee (IC) as required by the POSH Act to receive and inquire into complaints of sexual harassment. The IC shall be constituted as follows:</p>",
"<ul>",
"<li>A <strong>Presiding Officer</strong> who shall be a woman employed at a senior level in the workplace;</li>",
"<li>Not less than <strong>two members</strong> from among the employees, preferably committed to the cause of women or having experience in social work or legal knowledge;</li>",
"<li>One <strong>external member</strong> from a non-governmental organisation or association committed to the cause of women, or a person familiar with issues relating to sexual harassment; and</li>",
"<li>At least <strong>one-half</strong> of the total members of the IC shall be women.</li>",
"</ul>",
"<p>The names and contact details of the IC members shall be displayed prominently at the workplace. Members of the IC shall hold office for a term not exceeding three years. Where a member is or becomes unable to continue, or is found to have contravened the confidentiality or other requirements of the Act, that member shall be replaced.</p>",
"<h4>22.4 Complaint Procedure</h4>",
"<p>An aggrieved woman may make a written complaint of sexual harassment to the IC within three months from the date of the incident, and within three months of the last incident where there is a series of incidents. The IC may extend this period, for reasons recorded in writing, if it is satisfied that circumstances prevented timely filing. Where the woman is unable to make a complaint in writing, any IC member shall render reasonable assistance to her to put the complaint in writing. Where she is unable to make the complaint herself on account of physical or mental incapacity or death, her legal heir or other prescribed person may do so.</p>",
"<h4>22.5 Conciliation</h4>",
"<p>Before initiating an inquiry, and at the request of the aggrieved woman, the IC may take steps to settle the matter through conciliation &mdash; provided that no monetary settlement shall be made the basis of conciliation. If a settlement is arrived at, the IC shall record it and forward copies to the parties, and no further inquiry shall be conducted in respect of that complaint unless the settlement terms are not complied with.</p>",
"<h4>22.6 Inquiry and Timelines</h4>",
"<ul>",
"<li>The IC shall complete the inquiry within a period of <strong>90 days</strong> from the receipt of the complaint.</li>",
"<li>The inquiry shall follow the principles of natural justice: the respondent shall be given a copy of the complaint, an opportunity to respond, and an opportunity to be heard; both parties may present witnesses and documents; and neither party may bring a legal practitioner to represent them in the proceedings.</li>",
"<li>During the pendency of the inquiry, the IC may, on the written request of the aggrieved woman, recommend interim measures &mdash; for example, transferring the aggrieved woman or the respondent to another workstation, granting leave to the aggrieved woman of up to three months in addition to her normal entitlement, or restraining the respondent from reporting on her work performance.</li>",
"<li>On completion of the inquiry, the IC shall provide a report of its findings to the employer within <strong>10 days</strong>, and the report shall be made available to the parties.</li>",
"<li>The employer shall act upon the recommendations within <strong>60 days</strong> of receiving the report.</li>",
"</ul>",
"<h4>22.7 Action on Findings</h4>",
"<p>If the allegation is proved, the IC shall recommend action against the respondent, which may include action for misconduct under the Company&rsquo;s Standing Orders and this Handbook (up to and including dismissal), and may recommend that the Company deduct from the respondent&rsquo;s salary such sum as it considers appropriate to be paid to the aggrieved woman as compensation, determined having regard to the mental trauma, loss of career opportunity, medical expenses, the income and financial status of the respondent, and the feasibility of payment. If the allegation is not proved, the IC may recommend that no action be taken. If the IC concludes that the complaint was malicious or made knowing it to be false, it may recommend action against the complainant &mdash; provided that a mere inability to substantiate a complaint shall not by itself attract such action.</p>",
"<h4>22.8 Confidentiality</h4>",
"<p>The identity and address of the aggrieved woman, the respondent, the witnesses, any information relating to the conciliation and inquiry proceedings, the recommendations of the IC and the action taken shall not be published, communicated or made known to the public, press or media in any manner. Breach of confidentiality is itself an offence and will attract disciplinary action.</p>",
"<h4>22.9 Protection Against Retaliation</h4>",
"<p>No person shall victimise, threaten, intimidate or retaliate against an aggrieved woman, a witness, or any person assisting in an inquiry, for having filed or supported a complaint. Any act of retaliation shall be treated as a separate and serious act of misconduct.</p>",
"<h4>22.10 Awareness, Training and Annual Reporting</h4>",
"<p>The Company shall display the penal consequences of sexual harassment and the constitution of the IC at conspicuous places in the workplace; organise awareness programmes and orientation for employees and the IC at regular intervals; and provide the facilities necessary for the IC to conduct inquiries. The IC shall prepare an <strong>annual report</strong> of the number of complaints received and disposed of during the year, and the Company shall include the required particulars in its annual returns and forward the report to the District Officer as required by the POSH Act.</p>",

"<h3>23. Workplace Health &amp; Safety</h3>",
"<p>Safety is the first and non-negotiable priority at __COMPANY__. A garment factory contains many sources of hazard: high-speed sewing and cutting machines, knives and shears, steam boilers and irons, chemical dyes and spot-removers, large quantities of highly flammable fabric and lint, electrical installations, and material-handling operations. This chapter is to be read as a binding set of rules. It is framed in compliance with the Factories Act, 1948, and the rules made under it, and with the directions of the Inspector of Factories. Every employee, supervisor, contractor and visitor must comply. <strong>No production target, no buyer deadline and no instruction from any person ever justifies an unsafe act. Every employee has the right and the duty to stop work that is unsafe and to report it immediately.</strong></p>",
"<h4>23.1 General Safety Rules</h4>",
"<ul>",
"<li>Follow all safety instructions, signs, markings and the directions of supervisors and the Safety Officer at all times.</li>",
"<li>Operate only the machine or equipment you are trained and authorised to operate.</li>",
"<li>Keep gangways, aisles, staircases, exits and the area around machines, fire equipment and electrical panels clear and unobstructed at all times.</li>",
"<li>Do not run inside the factory; walk, and watch for moving trolleys and material handling.</li>",
"<li>Tie back long hair, avoid loose clothing, dupattas, scarves, dangling jewellery and bangles near rotating machinery, as these can be caught and cause severe injury.</li>",
"<li>Do not engage in horseplay, practical jokes, throwing of objects, or any distracting behaviour near machinery.</li>",
"<li>Report any unsafe condition, defective machine, exposed wire, leaking valve, oil spill or damaged guard to your supervisor at once and do not use the equipment until it is made safe.</li>",
"<li>Do not remove, deface or render ineffective any safety device, guard, fence, warning sign or notice.</li>",
"</ul>",
"<h4>23.2 Machine Guarding and Safe Operation</h4>",
"<p>All dangerous parts of machinery &mdash; including needle bars, pulleys, belts, gears, knives, cutters and rotating shafts &mdash; shall be securely fenced or guarded as required by the Factories Act, 1948. The following rules apply to all machine operation:</p>",
"<ul>",
"<li>Needle guards, eye guards, pulley covers and finger guards must be in place and functioning before a machine is started. Never operate a machine with a guard removed or by-passed.</li>",
"<li>Switch off and isolate a machine (lock-out / tag-out) before threading where required, clearing a jam, changing a needle or blade, cleaning, oiling or adjusting it. Never reach into a moving machine.</li>",
"<li>Cutting-room knives, band-knives, straight-knives and end-cutters shall be used only by trained cutters wearing the prescribed metal-mesh gloves, and shall be fitted with their blade guards.</li>",
"<li>Keep hands, fingers and tools clear of the needle and the blade at all times; use the correct feeding aids and guides.</li>",
"<li>Pressing and steam irons, boilers, fusing machines and calenders involve heat and pressure; operate them only with the prescribed guards, valves, gauges and protective equipment, and report any malfunction immediately.</li>",
"<li>Do not leave a running machine unattended; switch off at the end of work and during breaks.</li>",
"</ul>",
"<h4>23.3 Mandatory Personal Protective Equipment (PPE)</h4>",
"<p>The Company shall provide, free of cost, the personal protective equipment appropriate to each task. Wearing the prescribed PPE is mandatory; working without required PPE is a breach of safety rules and a punishable act of misconduct. The minimum PPE by area is set out below; the Safety Officer may prescribe additional protection for specific tasks.</p>",
"<table style='border-collapse:collapse;width:100%;border:1px solid #333;'>",
"<thead><tr style='background:#dce6f1;'>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Area / Activity</th>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Principal Hazard</th>",
"<th style='border:1px solid #333;padding:6px;text-align:left;'>Mandatory PPE</th>",
"</tr></thead>",
"<tbody>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Cutting room (straight / band knife)</td>",
"<td style='border:1px solid #333;padding:6px;'>Cuts, finger amputation</td>",
"<td style='border:1px solid #333;padding:6px;'>Metal-mesh / cut-resistant gloves, finger guard, safety footwear; eye protection where required</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Sewing / stitching lines</td>",
"<td style='border:1px solid #333;padding:6px;'>Needle injury, entanglement</td>",
"<td style='border:1px solid #333;padding:6px;'>Needle guard &amp; eye guard on machine, finger guard; hair tied back; no loose clothing or bangles</td>",
"</tr>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Pressing / finishing / fusing</td>",
"<td style='border:1px solid #333;padding:6px;'>Burns, steam, heat</td>",
"<td style='border:1px solid #333;padding:6px;'>Heat-resistant gloves / hand guard, apron; care near steam lines and valves</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Dyeing / washing / spotting (chemicals)</td>",
"<td style='border:1px solid #333;padding:6px;'>Chemical splash, fumes, skin/eye damage</td>",
"<td style='border:1px solid #333;padding:6px;'>Chemical-resistant gloves, apron, goggles / face shield, rubber boots, respirator / mask as specified</td>",
"</tr>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>Stores / warehouse / loading</td>",
"<td style='border:1px solid #333;padding:6px;'>Falling loads, manual handling</td>",
"<td style='border:1px solid #333;padding:6px;'>Safety shoes, gloves; helmet where overhead stacking exists</td>",
"</tr>",
"<tr style='background:#f2f2f2;'>",
"<td style='border:1px solid #333;padding:6px;'>Boiler / generator / maintenance / electrical</td>",
"<td style='border:1px solid #333;padding:6px;'>Burns, shock, mechanical injury</td>",
"<td style='border:1px solid #333;padding:6px;'>Insulated gloves, safety shoes, helmet, ear protection near generators, eye protection</td>",
"</tr>",
"<tr>",
"<td style='border:1px solid #333;padding:6px;'>High-lint / high-dust zones</td>",
"<td style='border:1px solid #333;padding:6px;'>Respiratory irritation</td>",
"<td style='border:1px solid #333;padding:6px;'>Dust mask / respirator as prescribed</td>",
"</tr>",
"</tbody>",
"</table>",
"<p>PPE shall be kept clean and in good condition; damaged or worn PPE must be reported and replaced. Tampering with, misusing, or refusing to wear prescribed PPE is misconduct.</p>",
"<h4>23.4 Prohibited Acts</h4>",
"<ul>",
"<li>Smoking, carrying matches or lighters, or using any open flame anywhere except in a designated smoking area (if any) far from fabric, lint and chemicals.</li>",
"<li>Operating any machine, electrical equipment, boiler or vehicle without authorisation and training.</li>",
"<li>Removing, by-passing or disabling any guard, interlock or safety device.</li>",
"<li>Overloading electrical points, racks, trolleys or lifts beyond rated capacity.</li>",
"<li>Blocking fire exits, fire extinguishers, hydrants, electrical panels or first-aid points with material.</li>",
"<li>Working under the influence of alcohol or drugs, or while excessively fatigued to a degree that endangers safety.</li>",
"<li>Carrying out unauthorised electrical or mechanical repairs.</li>",
"<li>Engaging in horseplay or distracting others near machinery.</li>",
"</ul>",
"<h4>23.5 Electrical Safety</h4>",
"<ul>",
"<li>Only authorised, qualified electricians may work on electrical installations, panels and wiring.</li>",
"<li>Report immediately any exposed wire, damaged plug, sparking, burning smell, frequent tripping or electric shock, and do not touch the equipment.</li>",
"<li>Do not use makeshift connections, multiple loose extensions or damaged cords. Switch off equipment at the mains when not in use and before cleaning.</li>",
"<li>Earth all machines properly; do not defeat earthing. Keep liquids and wet hands away from electrical points.</li>",
"<li>Electrical panels shall be kept closed, locked and unobstructed; rubber mats shall be provided in front of panels.</li>",
"</ul>",
"<h4>23.6 Fire Prevention and Emergency Evacuation</h4>",
"<p>Fabric, lint, packing material and chemicals make fire the single greatest hazard in a garment factory. Every employee must know the fire procedures.</p>",
"<ul>",
"<li>Keep the workplace free of accumulated lint, fabric scrap, oily rags and waste; do not let waste pile up near machines or electrical points.</li>",
"<li>Know the location of the nearest fire extinguisher, hose reel, fire alarm point and emergency exit from your workstation, and keep them clear at all times.</li>",
"<li>Fire-fighting equipment shall be maintained, inspected and never used for any other purpose.</li>",
"<li>On discovering a fire, raise the alarm immediately, alert others, and use the nearest appropriate extinguisher only if trained and only if the fire is small and you are not at risk.</li>",
"<li>On hearing the fire / evacuation alarm: stop work, switch off your machine if safe, do not stop to collect belongings, do not use lifts, move calmly to the nearest emergency exit and proceed to the designated assembly point.</li>",
"<li>Follow the instructions of fire wardens / floor marshals. Report to your section in-charge at the assembly point so that a head-count can confirm everyone is out.</li>",
"<li>Do not re-enter the building until the all-clear is given by the person in charge.</li>",
"<li>The Company shall conduct fire drills and evacuation drills at regular intervals; participation is mandatory.</li>",
"</ul>",
"<h4>23.7 First-Aid and Medical Facilities</h4>",
"<ul>",
"<li>First-aid boxes shall be provided and maintained at conspicuous, marked locations, in the number and contents required by the Factories Act, 1948, in the charge of trained first-aiders.</li>",
"<li>An ambulance room / dispensary and qualified medical assistance shall be provided where required by law for the size of the workforce.</li>",
"<li>Any injury, however minor &mdash; including a needle prick, cut or burn &mdash; must be reported and treated at once, and recorded in the accident register.</li>",
"<li>Employees should know who the trained first-aiders on their floor are and how to summon emergency help.</li>",
"</ul>",
"<h4>23.8 Handling of Chemicals, Dyes and Hazardous Materials</h4>",
"<ul>",
"<li>Chemicals, dyes, solvents, spot-removers, adhesives and cleaning agents shall be stored in labelled containers in designated, ventilated areas, away from heat, food and incompatible materials.</li>",
"<li>Material Safety Data Sheets (MSDS) shall be available for hazardous substances, and handlers shall be trained in their safe use, the hazards involved and the first-aid measures.</li>",
"<li>Use the prescribed PPE (gloves, goggles, apron, respirator) when handling chemicals; never decant chemicals into unlabelled or food containers.</li>",
"<li>Ensure adequate ventilation; avoid inhaling fumes; do not eat, drink or smoke in chemical-handling areas.</li>",
"<li>Clean up spills immediately following the prescribed procedure, and dispose of chemical waste and contaminated material only through the authorised waste channel &mdash; never into ordinary drains or general waste.</li>",
"</ul>",
"<h4>23.9 Accident and Near-Miss Reporting</h4>",
"<p>Every accident, injury, dangerous occurrence and near-miss must be reported, however minor it appears. A near-miss &mdash; an event that could have caused injury or damage but did not &mdash; is a free warning, and reporting it allows us to prevent a future accident.</p>",
"<ul>",
"<li>The injured person, or any witness, shall report the event to the supervisor immediately; the supervisor shall arrange first-aid / medical attention and inform the Safety Officer and Human Resources.</li>",
"<li>All accidents and dangerous occurrences shall be recorded in the accident register, investigated to find the root cause, and corrective action taken.</li>",
"<li>Notifiable accidents and dangerous occurrences shall be reported to the Inspector of Factories and other authorities within the time and manner prescribed by the Factories Act, 1948.</li>",
"<li>Reporting a genuine accident or near-miss shall never attract punishment for the act of reporting; concealing an accident, on the other hand, is itself misconduct.</li>",
"</ul>",
"<h4>23.10 Safety Committee</h4>",
"<p>The Company shall constitute a Safety Committee with equal representation of management and workers, as contemplated by the Factories Act, 1948, and the State Factory Rules. The Safety Committee shall meet at regular intervals to review safety performance, accident and near-miss reports, the adequacy of guards and PPE, the results of drills, and unsafe conditions reported by workers, and shall recommend corrective and preventive measures. Where the workforce strength so requires, a qualified Safety Officer shall be appointed.</p>",
"<h4>23.11 Welfare and Statutory Compliance</h4>",
"<p>The Company shall maintain the welfare and working-condition standards required by the Factories Act, 1948, including cleanliness, adequate ventilation and lighting, control of dust and lint, drinking water, sufficient and separate latrines and urinals for men and women, washing facilities, sitting and rest arrangements where applicable, a canteen and crèche where the prescribed thresholds are met, and the limits on working hours, overtime, weekly rest and the employment of women as laid down in the Act. Compliance with the Factories Act, the rules made under it, and the directions of the Inspector of Factories is mandatory for all.</p>",

"<h3>24. Quality, 5S, Housekeeping &amp; Material Discipline</h3>",
"<p>Quality is what keeps __COMPANY__&rsquo;s buyers coming back, and a clean, orderly factory is the foundation of both quality and safety. Every employee is responsible for the quality of their own work and for the condition of their workplace.</p>",
"<h4>24.1 Quality Standards</h4>",
"<ul>",
"<li>Every operation shall be performed to the specification, tech-pack, sample and tolerance approved for the order. If you are unsure of a specification, ask your supervisor before proceeding &mdash; do not guess.</li>",
"<li>Check the work received from the previous operation and your own output; do not pass on a known defect.</li>",
"<li>Follow the prescribed inspection points, AQL sampling and in-line / end-line checks. Report defect patterns early so the cause can be fixed at source.</li>",
"<li>Do not use unapproved substitute materials, trims or methods to meet a target.</li>",
"</ul>",
"<h4>24.2 Rejection and Rework</h4>",
"<p>Defective work shall be segregated, clearly identified and routed for rework or rejection in accordance with the quality procedure. Rework shall be carried out only with proper authorisation and shall itself be re-inspected. Rejected and second-quality goods shall be controlled and accounted for; they must never be removed from the factory except through the authorised channel. Deliberately mixing rejects into good stock, or passing rejects as first quality, is misconduct.</p>",
"<h4>24.3 5S and Housekeeping</h4>",
"<p>__COMPANY__ follows the 5S system as the basis of an organised, efficient and safe workplace:</p>",
"<ul>",
"<li><strong>Sort (Seiri)</strong> &mdash; keep only what is needed at the workstation; remove unnecessary items, scrap and clutter.</li>",
"<li><strong>Set in order (Seiton)</strong> &mdash; a place for everything and everything in its place; tools, bobbins, trims and materials kept in marked locations.</li>",
"<li><strong>Shine (Seiso)</strong> &mdash; clean your machine and area at prescribed times; remove lint, dust, oil and waste.</li>",
"<li><strong>Standardise (Seiketsu)</strong> &mdash; follow the agreed standards and visual controls so that order is maintained the same way by everyone.</li>",
"<li><strong>Sustain (Shitsuke)</strong> &mdash; make 5S a daily habit and a matter of discipline, not a one-time clean-up.</li>",
"</ul>",
"<p>Each employee is responsible for the cleanliness and orderliness of their workstation, and each section is responsible for its common areas. Lint, fabric scrap and oily waste must be cleared regularly into the correct bins, both for quality and for fire safety.</p>",
"<h4>24.4 Material Discipline and Prevention of Pilferage</h4>",
"<p>Fabric and trims are the Company&rsquo;s most valuable materials, and the most vulnerable to waste and pilferage. Every employee handling material shares responsibility for protecting it:</p>",
"<ul>",
"<li>Draw, issue and consume material only against proper documents and against the approved cut plan and consumption norms; account for all material received.</li>",
"<li>Handle fabric and garments cleanly to avoid soiling, oil marks and damage; control cut-pieces, bundles and trims so they are not lost or mixed.</li>",
"<li>Return surplus material, end-bits, leftover trims and waste to stores or the designated collection point; do not retain or remove them.</li>",
"<li>Scrap, cut-waste and reject material shall be weighed, recorded and disposed of only through the authorised process.</li>",
"<li>No fabric, garment, trim, accessory, sample, tool or scrap may be taken out of the factory without a proper, authorised gate pass. All persons and bags are subject to security checks at the gate.</li>",
"<li>The removal of any material from the premises without authority is theft / pilferage and is grave misconduct attracting dismissal and, where applicable, criminal prosecution.</li>",
"</ul>",

"<h3>25. Anti-Bribery &amp; Anti-Corruption</h3>",
"<p>__COMPANY__ has zero tolerance for bribery and corruption in any form, whether involving public officials or private parties, and whether the Company would gain or lose by it. Corruption damages the Company&rsquo;s reputation, exposes it and its employees to legal liability, distorts decisions, and ultimately costs jobs. This policy applies to all employees and to everyone who acts for or on behalf of the Company, including agents, contractors and intermediaries.</p>",
"<h4>25.1 The Rule</h4>",
"<p>No employee shall, directly or through any other person:</p>",
"<ul>",
"<li>Offer, promise, give, solicit, accept or receive any bribe, kickback, secret commission, illegal gratification or other improper benefit;</li>",
"<li>In order to obtain or retain business, an order, a favourable price, an approval, a certificate, a passing inspection, or any other improper advantage; or to induce any person to act improperly or to reward them for doing so.</li>",
"</ul>",
"<p>A &lsquo;bribe&rsquo; can take many forms beyond cash: gifts of value, hospitality, travel, employment for a relative, discounts, loans, donations made on someone&rsquo;s behalf, or any other thing of value given or received to improperly influence a decision.</p>",
"<h4>25.2 Suppliers and Sub-Contractors</h4>",
"<p>Employees in purchasing, sourcing, stores and accounts must select and deal with suppliers, job-workers, transporters and contractors on the basis of merit &mdash; quality, price, reliability and compliance &mdash; and never in exchange for a personal benefit. Accepting a commission or kickback from a supplier in return for an order, an inflated price, accepting sub-standard goods, or releasing payment is a grave breach and is specifically listed as major misconduct in Chapter 19.</p>",
"<h4>25.3 Buyers and Their Representatives</h4>",
"<p>Employees in merchandising, sales, quality and shipping must not offer or give any improper inducement to a buyer, a buyer&rsquo;s representative, a buying house, or a third-party inspector to secure an order, to obtain a favourable comment, or to pass an inspection. Likewise, no employee shall solicit or accept any personal payment from a buyer&rsquo;s side. Legitimate, modest and openly-given business hospitality, within the limits of Chapter 18, is permitted; covert payments are not.</p>",
"<h4>25.4 Inspectors, Auditors and Officials</h4>",
"<p>Compliance audits, social audits, quality inspections and statutory inspections are part of our business. Employees shall cooperate honestly with auditors, inspectors and government officials, and shall provide truthful information and genuine records. No employee shall offer or pay any bribe, &lsquo;speed money&rsquo; or facilitation payment to any inspector, auditor or public official to obtain a clearance, a favourable report, or to avoid a penalty. Any demand for such a payment shall be declined and reported to management.</p>",
"<h4>25.5 Records, Donations and Facilitation Payments</h4>",
"<ul>",
"<li>All payments and receipts must be properly recorded in the Company&rsquo;s books with accurate descriptions; no &lsquo;off-book&rsquo; funds, false invoices or disguised entries may be created or used for any purpose.</li>",
"<li>Facilitation payments &mdash; small payments to secure or speed up routine official action &mdash; are prohibited.</li>",
"<li>Charitable or other donations shall be made only with proper authorisation and never as a disguised bribe or as a condition of obtaining business or a favour.</li>",
"</ul>",
"<h4>25.6 Reporting and Protection</h4>",
"<p>Every employee has a duty to report, promptly and in good faith, any actual or suspected bribery, corruption, kickback or related wrongdoing. Reports may be made to the reporting manager, to Human Resources, or to senior management. The Company shall keep the identity of a person making a good-faith report confidential to the extent practicable, shall investigate fairly, and shall protect that person from retaliation, victimisation or any adverse treatment for having reported. Retaliation against a person who reports in good faith is itself a serious act of misconduct. Knowingly making a false or malicious allegation, however, is also misconduct. Breach of this Anti-Bribery &amp; Anti-Corruption policy is treated as major misconduct under Chapter 19 and may attract dismissal and, where the conduct is a criminal offence, referral to the authorities.</p>"
].join("");
